// Generated by CoffeeScript 1.3.3
(function() {
  var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  window.utils = {
    isUIWebView: /(iPhone|iPod|iPad).*AppleWebKit(?!.*Safari)/i.test(navigator.userAgent),
    isMobileSafariOrUIWebView: /(iPhone|iPod|iPad).*AppleWebKit/i.test(navigator.userAgent),
    isLatLng: function(latLngArray) {
      if ((!(latLngArray != null)) || (latLngArray.length === !2) || isNaN(latLngArray[0]) || isNaN(latLngArray[1])) {
        return false;
      } else {
        return true;
      }
    },
    isTouchDevice: function() {
      var isTouch;
      isTouch = !!(__indexOf.call(window, 'ontouchstart') >= 0);
      this.isTouchDevice = function() {
        return isTouch;
      };
      return isTouch;
    },
    log: function(msg) {
      if (window.console && window.console.log) {
        return window.console.log(msg);
      }
    }
  };

}).call(this);
